server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8088"
  cloud:
    gateway:
      mvc:
        routes:
          - id: employee-service
            uri: lb://employee-service
            predicates: path=/employee/**
          - id: department-service
            uri: lb://department-service
            predicates: path=/employee/**
